version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
  build:
    commands:
      - npm run build
#      - npm run test
      - npm run lint
      - npm run package
artifacts:
  base-directory: dist
  files: '**/*'
  discard-paths: no
